#!/bin/sh

echo "what will the name of the man page be ?"
read manname

echo "# Name: 
- The name of the command and a pithy one-liner that describes its function.

# Synopsis: 
- A terse description of the invocations someone can use to launch the program. These show the types of accepted command-line parameters.

# Description: 
- A description of the command or function.

# Options: 
- A list of command-line options, and what they do.

# Examples: 
- Some examples of common usage.

# Exit Values: 
- The possible return codes and their meanings.

# Bugs: 
- A list of known bugs and quirks. Sometimes, this is supplemented with (or replaced by) a link to the issue tracker for the project.

# Author: 
- The person or people who wrote the command.

# Copyright: 
- Your copyright message. These also usually include the type of license under which the program is released.
" >> $manname.1.md

vim $manname.1.md

# lets you preview the manpage
pandoc $manname.1.md -s -t man | /usr/bin/man -l -

# creating the manpage
pandoc $manname.1.md -s -t man -o $manname.1

# list the paths for man pages
manpath

# here im using the home manpath if necessary you should change this path
# you can get a list of all paths using the manpath command and decide from there

path_="~/.local/share/man/man1"

mv $manname.1 $path_/

# creating the compressed format for man to read
gzip $path_/$manname.1

# update the man database
mandb

man $manname
